/*
 * @Author: NoRain 
 * @Date: 2023-03-03 17:31:59 
 * @Last Modified by: NoRain
 * @Last Modified time: 2023-03-03 17:37:39
 */
export default class Physics3DUtils {

    /**自定义过滤1 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER1: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER1;
    /**自定义过滤2 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER2: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER2;
    /**自定义过滤3 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER3: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER3;
    /**自定义过滤4 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER4: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER4;
    /**自定义过滤5 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER5: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER5;
    /**自定义过滤6 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER6: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER6;
    /**自定义过滤7 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER7: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER7;
    /**自定义过滤8 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER8: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER8;
    /**自定义过滤9 */
    static COLLISIONFILTERGROUP_CUSTOMFILTER9: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER9;
    /**自定义过滤10*/
    static COLLISIONFILTERGROUP_CUSTOMFILTER10: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_CUSTOMFILTER10;
    /**所有过滤 */
    static COLLISIONFILTERGROUP_ALLFILTER: number = Laya.Physics3DUtils.COLLISIONFILTERGROUP_ALLFILTER;



}