/*
 * @Author: NoRain 
 * @Date: 2023-02-18 09:47:37 
 * @Last Modified by: NoRain
 * @Last Modified time: 2023-02-18 10:08:52
 */

export enum LocalizationKeyEnum {
    "GAME_START" = "GAME_START",
    "OK" = "OK",
    "CANCEL" = "CANCEL",
    "SETTING" = "SETTING",
    "BGM" = "BGM",
    "SFX" = "SFX",
    "SHAKE" = "SHAKE",
    "LANGUAGE" = "LANGUAGE",
    "SUPPORT" = "SUPPORT",
    "ON" = "ON",
    "OFF" = "OFF",
    "CONGRATULATIONS" = "CONGRATULATIONS",
    "OPENNOW" = "OPENNOW",
    "LUCKYBOXBRONZE" = "LUCKYBOXBRONZE",
    "LUCKYBOXSILVER" = "LUCKYBOXSILVER",
    "LUCKYBOXGOLD" = "LUCKYBOXGOLD",
    "LUCKYBOXDIAMOND" = "LUCKYBOXDIAMOND",
    "LUCKYBOXPLATINUM" = "LUCKYBOXPLATINUM",
    "PRIVACYAGREEMENT" = "PRIVACYAGREEMENT",
    "SHOP" = "SHOP",
    "RANKING" = "RANKING",
    "GOLD" = "GOLD",
    "DIAMOND" = "DIAMOND",
    "HOT" = "HOT",
    "BEST" = "BEST",
    "YOUDONTHAVEENOUGHDIAMONDS" = "YOUDONTHAVEENOUGHDIAMONDS",
    "NOTYETIMPLEMENTED" = "NOTYETIMPLEMENTED",
    "CONGRATULATIONSONGETTING"="CONGRATULATIONSONGETTING"

}